# Generated by Django 3.2 on 2021-04-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grabaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grabacionesId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('outputMode', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('recordingLayout', models.CharField(blank=True, max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('size', models.IntegerField(blank=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('url', models.URLField(blank=True)),
                ('hasAudio', models.BooleanField(blank=True)),
                ('hasVideo', models.BooleanField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.CharField(max_length=100)),
                ('stateLicense', models.BooleanField(verbose_name='Estado del Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('users_group', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeUser', models.CharField(choices=[('AG', 'Agente'), ('SU', 'Supervisor'), ('AD', 'Administrador')], max_length=10, verbose_name='Tipo de Usuario')),
                ('licenseUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabaciones.license', verbose_name='Tipo Licencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario plataforma')),
                ('user_groups', models.ManyToManyField(blank=True, to='grabaciones.UserGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente con sesion')),
            ],
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['clientId'], name='grabaciones_clientI_83c8f3_idx'),
        ),
        migrations.AddField(
            model_name='grabaciones',
            name='sessionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabaciones.session', verbose_name='Sesion asociada'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['sessionId'], name='grabaciones_session_c0c2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='grabaciones',
            index=models.Index(fields=['grabacionesId'], name='grabaciones_grabaci_eb8d56_idx'),
        ),
    ]
