# Generated by Django 3.2 on 2021-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabaciones', '0002_auto_20210426_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabAdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('task_name', models.CharField(max_length=200, null=True)),
                ('task_by', models.TextField(max_length=10)),
                ('value', models.TextField(max_length=10)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAIL', 'FAIL'), ('RUNNING', 'RUNNING')], max_length=30, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='grabadit',
            index=models.Index(fields=['date'], name='grabaciones_date_43b15a_idx'),
        ),
        migrations.AddIndex(
            model_name='grabadit',
            index=models.Index(fields=['task_name'], name='grabaciones_task_na_e4f932_idx'),
        ),
    ]
